# Generated by Django 5.0.3 on 2024-03-17 09:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_rename_post_پست'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='پست',
            new_name='Post',
        ),
    ]
