# Generated by Django 5.0.3 on 2024-03-17 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_پست_post'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'verbose_name': 'پست', 'verbose_name_plural': 'پست\u200cها'},
        ),
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(default='sdfsdfd'),
            preserve_default=False,
        ),
    ]
